coursework/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'),),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'main'

urlpatterns = [
    path('', ChannelShowTimeListView.as_view(), name='tvshows'),
    path('tvshows/<int:pk>', TVShowDetailView.as_view(), name='tvshow_detail'),
    path('channel/<int:pk>/<str:start_date>/', ChannelDetailView.as_view(), name='channel_detail_with_date'),
    path('channel/<int:pk>/', ChannelDetailView.as_view(), name='channel_detail_without_date'),

    path('channels/new/', ChannelCreateView.as_view(), name='channel_create'),
    path('channels/<int:pk>/edit/', ChannelUpdateView.as_view(), name='channel_update'),
    path('channels/<int:pk>/delete/', ChannelDeleteView.as_view(), name='channel_delete'),

    path('tvshows/new/', TVShowCreateView.as_view(), name='tvshow_create'),
    path('tvshows/<int:pk>/edit/', TVShowUpdateView.as_view(), name='tvshow_update'),
    path('tvshow/<int:pk>/delete/', TVShowDetailView.as_view(), name='tvshow_delete'),

    path('showtime/new/', ChannelShowTimeCreateView.as_view(), name='showtime_create'),
    path('showtime/<int:pk>/edit/', ChannelShowTimeUpdateView.as_view(), name='showtime_update'),
    path('showtime/<int:pk>/delete/', ChannelShowTimeDeleteView.as_view(), name='showtime_delete'),

    path('login/', CustomLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
]

templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h1 class="mb-3 text-center">Welcome, {{ user.username }}!</h1>

    <h3>All Channels</h3>
    <ul>
        {% for channel in channels %}
            <li><a class="link" href="{% url 'main:channel_detail_without_date' channel.id %}">{{ channel.name }}</a></li>
        {% endfor %}
    </ul>
   <a class="btn btn-primary mb-5" href="{% url 'main:channel_create'%}">Add Channel</a>

    <h3>All Shows</h3>
    <ul>
        {% for show in shows %}
            <li>
                <a class="link" href="{% url 'main:tvshow_detail' show.id %}">{{ show.name }}</a>
                {% if show.category %}
                    <span class="category-label mx-2">{{ show.get_category_full }}</span>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <a class="btn btn-primary mb-5" href="{% url 'main:tvshow_create'%}">Add Show</a>

<h3>All Channel Show Times</h3>
<a href="{% url 'main:showtime_create' %}" class="btn btn-primary mb-3">Add Channel Show Time</a>
<ul>
    {% for cst in channel_showtimes %}
        <li class="mb-2">
            {{ cst.channel.name }} - {{ cst.show.name }}:
            <span class="fw-bold">   {{ cst.start_time|date:"dM, Y H:i" }} - {{ cst.get_end_time|date:"dM, Y H:i" }}</span>
            <a href="{% url 'main:showtime_update' cst.id %}" class="btn btn-warning mx-3">Edit</a>
            <a href="{% url 'main:showtime_delete' cst.id %}" class="btn btn-danger" onclick="return confirmDelete();">Delete</a>
        </li>
    {% endfor %}
</ul>

</div>
{% endblock %}
{% block afterscripts %}
<script>
   function confirmDelete() {
       return confirm('Are you sure you want to delete this?');
   }
</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Sans:ital,wght@0,100..800;1,100..800&display=swap"
              rel="stylesheet">
        <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% endblock %}
</head>
<body>
<nav class="nav">
    <div class="container d-flex py-4 justify-content-between align-items-center">
        <a class="navbar-brand" href="{% url 'main:tvshows' %}">TVprogram</a>
        <ul class="d-flex gap-3 p-0 m-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="POST" action="{% url 'main:logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-primary" type="submit">Logout</button>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url 'main:account' %}">Account</a>
                </li>
            {% else %}
              {% if request.path != '/login/' %}
                <li class="nav-item">
                    <a class="btn btn-primary" href="{% url 'main:login' %}">Login</a>
                </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
{% endblock %}
 {% block afterscripts %}{% endblock %}
</body>
</html>

templates/channel_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-3">
        <div class="card card-detail p-4 text-center">
            <img class="mb-3 mx-auto" style="width: 200px;" src="{{ channel.image.url }}" alt="{{ channel.name }}">
            <h2>{{ channel.name }}</h2>
            <p class="mb-4">{{ channel.description }}</p>

            {% if user.is_authenticated %}
                <div class="mb-4">
                    <a href="{% url 'main:channel_update' channel.id %}" class="btn btn-warning">Edit Channel</a>
                    <a href="{% url 'main:channel_delete' channel.id %}" class="btn btn-danger" onclick="return confirmDelete();">Delete Channel</a>
                </div>
            {% endif %}

       <h2 class="mb-3">Shows for the upcoming week:</h2>

            {% for day, shows in shows_by_day.items %}
                <h3>{{ day|date:"l, d M" }}</h3>
                <ul style="list-style: none;">
                    {% for showtime in shows %}
                        <li>
                            <a class="link" href="{% url 'main:tvshow_detail' showtime.show.id %}">{{ showtime.show.name }}</a>
                            <p class="fw-bold fs-18">{{ showtime.start_time|date:"H:i" }} - {{ showtime.get_end_time|date:"H:i" }}</p>
                        </li>
                    {% endfor %}
                </ul>
            {% empty %}
                <p>No shows scheduled for the upcoming week.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block afterscripts %}
<script>
   function confirmDelete() {
       return confirm('Are you sure you want to delete this channel?');
   }
</script>
{% endblock %}

templates/channel_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if object %}
        <h2 class="mt-3">Edit Channel</h2>
    {% else %}
        <h2 class="mt-3">Create Channel</h2>
    {% endif %}
    
    <form method="post" action="" enctype="multipart/form-data" style="max-width: 500px;">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/channelshowtime_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if object %}
        <h2 class="mt-3">Edit Show Time</h2>
    {% else %}
        <h2 class="mt-3">Create Show Time</h2>
    {% endif %}

    <form method="post" action="" style="max-width: 400px;">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <form method="post" action="{% url 'main:login' %}" class="card p-4 m-auto mt-3" style="max-width: 400px;">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
    </div>

{% endblock %}

templates/tv_program.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">
        <div class="d-flex justify-content-between mb-4">
            <h2>TV Program</h2>
            <form class="d-flex gap-4 align-items-center" method="GET" action="">
                <div class="d-flex gap-3 align-items-center">
                    <label class="form-label mb-0" for="sort" style="text-wrap: nowrap;">Sort by:</label>
                    <select class="custom-control" name="sort" id="sort">
                        <option value="channels" {% if form.sort == 'channels' %}selected{% endif %}>Channels</option>
                        <option value="time" {% if form.sort == 'time' %}selected{% endif %}>Time</option>
                    </select>
                </div>
                <div class="d-flex gap-3 align-items-center">
                    <label class="form-label mb-0" for="start_date" style="text-wrap: nowrap;">Select day:</label>
                    <input class="custom-control" type="date" id="start_date" name="start_date"
                           value="{{ start_date }}">
                </div>
                <button class="btn btn-outline-primary" type="submit">Filter</button>
            </form>
        </div>
        {% if request.GET.sort == 'channels' %}
            {% if channel_data %}
            <div class="channels-grid">
                {% for channel, shows in channel_data.items %}
                    <div class="card card-channel p-3 d-flex flex-column gap-3">
                        <h2 class="text-center">{{ channel }}</h2>
                        <img src="{{ channel.image.url }}" class="d-block m-auto" style="max-width: 100px;" alt="">
                        <ul class="p-0 m-0 d-flex flex-column gap-2">
                            {% for show in shows %}
                                <li class="d-flex justify-content-between align-items-center">
                                    <span class="time fw-bold">{{ show.start_time|date:"H:i" }} - {{ show.end_time|date:"H:i" }}</span>
                                    <div class="d-flex gap-2 align-items-center">
                                        <a class="link" href="{% url 'main:tvshow_detail' show.show_id %}">{{ show.show }}</a>
                                        {% if show.show_category%}
                                            <span class="category-label">{{ show.show_category }}</span>
                                        {% endif %}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                        <a class="btn btn-outline-primary w-100" href="{{ channel_detail_url }}">See more</a>
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <h4 class="text-center mt-4">No shows on this day</h4>
            {% endif %}
        {% elif request.GET.sort == 'time' %}
            {% if channel_showtimes %}
            <ul>
                {% for cst in channel_showtimes %}
                    <li>
                        <div class="d-flex align-items-center gap-3">
                            <a class="link" href="{% url 'main:tvshow_detail' cst.show_id %}">{{ cst.show.name }}</a>
                            <span class="category-label">{{ cst.show.category }}</span>
                            <span class="fw-bold fs-18">{{ cst.start_time|date:"H:i" }} - {{ cst.get_end_time|date:"H:i" }}</span>
                            <a class="link" href="{{ channel_detail_url }}">({{ cst.channel.name }})</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <h4 class="text-center mt-4">No shows on this day</h4>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/tvshow_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <div class="card card-detail p-4 text-center">
            <img class="mb-3 mx-auto" style="width: 200px;" src="{{ show.image.url }}" alt="{{ show.name }}">
            <div class="d-flex gap-3 align-items-center justify-content-center mb-3">
                <h2 class="mb-0">{{ show.name }}</h2>
                {% if show.category %}
                    <span class="category-label">{{ show.get_category_full }}</span>
                {% endif %}
            </div>
            <p class="mb-5">{{ show.description }}</p>
            {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'main:tvshow_update' show.id %}" class="btn btn-warning">Edit Show</a>
                    <a href="{% url 'main:tvshow_delete' show.id %}" class="btn btn-danger" onclick="return confirmDelete();">Delete Show</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block afterscripts %}
<script>
   function confirmDelete() {
       return confirm('Are you sure you want to delete this show?');
   }
</script>
{% endblock %}

templates/tvshow_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if object %}
        <h2 class="mt-3">Edit TV Show</h2>
    {% else %}
        <h2 class="mt-3">Create TV Show</h2>
    {% endif %}
    
    <form method="post" action="" enctype="multipart/form-data" style="max-width: 500px;">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}